update_interval: 100
results_limit: 5
depth_streams:
  - btcusdt
  - btcbusd
  - btcusdc
  - usdtbtc
  - busdbtc
  - usdcbtc
  - ethusdt
  - ethbusd
  - ethusdc
  - usdteth
  - busdeth
  - usdceth
  - bnbusdt
  - bnbbusd
  - bnbusdc
  - usdtbnb
  - busdbnb
  - usdcbnb
  - aptusdt
  - aptbusd
  - aptusdc
  - usdtapt
  - busdapt
  - usdcapt
  - btceth
  - ethbtc
  - btcbnb
  - bnbbtc
  - ethbnb
  - bnbeth
  - btcapt
  - aptbtc
  - apteth
  - ethapt
  - bnbapt
  - aptbnb
  - xrpusdt
  - xrpbusd
  - xrpusdc
  - usdtxrp
  - busdxrp
  - usdcxrp
  - btcxrp
  - xrpbtc
  - ethxrp
  - xrpeth
  - bnbxrp
  - xrpbnb
  - solusdt
  - solbusd
  - solusdc
  - usdtsol
  - busdsol
  - usdcsol
  - btcsol
  - solbtc
  - ethsol
  - soleth
  - bnbsol
  - solbnb


triangles:
  - parts: [btc, eth, bnb]
    pairs: [ethbtc, bnbeth, bnbbtc] 
    # First is correct I think
    # example(start and end with the same):
    # BTC -> ETH, ETH -> BNB, BNB -> BTC
  - parts: [btc, xrp, eth]
    pairs: [xrpbtc, xrpeth, ethbtc]
  - parts: [usdc, eth, btc]
    pairs: [ethusdc, ethbtc, btcusdc]
  - parts: [usdc, xrp, eth]
    pairs: [xrpusdc, xrpeth, ethusdc]
  - parts: [usdc, xrp, bnb]
    pairs: [xrpusdc, xrpbnb, bnbusdc]
  - parts: [usdt, xrp, eth]
    pairs: [xrpusdt, xrpeth, ethusdt]
  - parts: [usdt, xrp, bnb]
    pairs: [xrpusdt, xrpbnb, bnbusdt]
  - parts: [usdt, sol, btc]
    pairs: [solusdt, solbtc, btcusdt]
  - parts: [usdt, sol, bnb]
    pairs: [solusdt, solbnb, bnbusdt]
  - parts: [usdt, btc, busd]
    pairs: [usdtbtc, btcbusd, busdusdt]
  - parts: [usdt, btc, busd]
    pairs: [btcusdt, btcbusd, busdusdt]
  - parts: [usdt, btc, busd]
    pairs: [btcusdt, btcbusd, busdbtc]
  - parts: [usdt, btc, busd]
    pairs: [btcbusd, busdusdt, usdtbtc]
  - parts: [usdt, btc, ltc]
    pairs: [usdtbtc, btcltc, ltcusdt]
  - parts: [usdt, sol, btc]
    pairs: [usdtsol, solbtc, btcusdt]
  - parts: [usdt, sol, btc]
    pairs: [usdtbtc, btcsol, solusdt]
  - parts: [usdt, bnb, btc]
    pairs: [usdtbnb, bnbbtc, btcusdt]
  - parts: [usdt, bnb, btc]
    pairs: [usdtbtc, btcbnb, bnbusdt]
  - parts: [busd, bnb, btc]
    pairs: [busdbnb, bnbbtc, btcbusd]
  - parts: [usdt, bnb, btc]
    pairs: [busdbtc, btcbnb, bnbbusd]
  - parts: [usdt, busd, btc]
    pairs: [usdtbusd, busdbtc, btcusdt]
  - parts: [usdt, busd, btc]
    pairs: [busdusdt, usdtbtc, btcbusd]
